[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Custom derive required by the relm crate."
documentation = "https://docs.rs/relm-derive/"
license = "MIT"
name = "relm-derive"
repository = "https://github.com/antoyo/relm"
version = "0.9.2"

[lib]
proc-macro = true

[dependencies]
quote = "^0.3.14"
syn = "^0.11.8"

[dependencies.relm-gen-widget]
path = "../relm-gen-widget"
version = "^0.9.0"
