[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "webkit-test"
version = "0.1.0"

[dependencies]
futures = "^0.1.10"
gtk = "^0.1.2"
relm = "^0.9.0"
relm-attributes = "^0.9.0"
relm-derive = "^0.9.0"

[dependencies.webkit2gtk]
git = "https://github.com/antoyo/webkit2gtk-rs"
version = "^0.1"
