[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "relm-derive-common"
version = "0.9.0"

[dependencies]
quote = "^0.3.15"
syn = "^0.11.11"

[dependencies.relm-gen-widget]
path = "../relm-gen-widget"
version = "^0.9.0"
