[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Asynchronous, GTK+-based, GUI library, inspired by Elm, written in Rust"
documentation = "https://docs.rs/relm/"
license = "MIT"
name = "relm"
repository = "https://github.com/antoyo/relm"
version = "0.9.5"

[badges]
travis-ci = { repository = "antoyo/relm" }
appveyor = { repository = "antoyo/relm" }

[dependencies]
futures = { git = "https://github.com/alexcrichton/futures-rs", branch = "spawn-trait" }
futures-glib = { git = "https://github.com/antoyo/futures-glib-rs" }
glib = "^0.1.2"
glib-itc = "^0.1.1"
gobject-sys = "^0.3.3"
gtk = "^0.1.1"
gtk-sys = "^0.3.3"
log = "^0.3.7"

[dependencies.relm-core]
path = "relm-core"
version = "^0.1.1"

[dev-dependencies]
base64 = "^0.4.0"
blake2 = "^0.4.0"
byteorder = "^1.0.0"
chrono = "^0.3.0"
rand = "^0.3.15"
simplelog = "^0.4.2"
tokio-core = "^0.1.4"
tokio-proto = "^0.1.0"
tokio-service = "^0.1.0"
twist = "^0.5.0"
url = "^1.4.0"

[dev-dependencies.relm-derive]
path = "relm-derive"
version = "^0.9.0"

[dev-dependencies.relm-test]
path = "relm-test"
version = "^0.1.0"

[dev-dependencies.relm-attributes]
path = "relm-attributes"
version = "^0.9.0"

[features]
nightly = []
use_impl_trait = []

[package.metadata.release]
pre-release-replacements = [
    {file="README.adoc", search="relm = \"[a-z0-9^\\.-]+\"", replace="relm = \"{{version}}\""},
    {file="src/lib.rs", search="relm = \"[a-z0-9^\\.-]+\"", replace="relm = \"{{version}}\""},
    {file="examples/buttons-derive/Cargo.toml", search="relm = \"[a-z0-9^\\.-]+\"", replace="relm = \"{{version}}\""},
]

[replace]
"futures:0.1.13" = { git = "https://github.com/alexcrichton/futures-rs", branch = "spawn-trait" }
