[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["asynchronous", "gui"]
description = "Core streams and event loop primitives for asynchronous GUI in Rust. Foundation for the relm crate."
documentation = "https://docs.rs/relm-core/"
license = "MIT"
name = "relm-core"
repository = "https://github.com/antoyo/relm"
version = "0.1.4"

[dependencies]
futures = { git = "https://github.com/alexcrichton/futures-rs" }
futures-glib = { git = "https://github.com/antoyo/futures-glib-rs" }
gtk = "^0.1.1"

[dev-dependencies]
chrono = "^0.3.0"
glib = "^0.1.2"

[replace]
"futures:0.1.13" = { git = "https://github.com/alexcrichton/futures-rs" }
