[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "relm-state"
version = "0.1.0"

[dependencies]
futures = "^0.1.14"
log = "^0.3.7"

[dependencies.futures-glib]
git = "https://github.com/antoyo/futures-glib-rs"

[dependencies.relm-core]
path = "../relm-core"
version = "^0.1.1"
